import com.stepsoln.core.rules.requirements.CaseData;
import com.stepsoln.core.rules.RulesResponse;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.ArrayUtils;
import com.stepsoln.core.db.cases.*;
import com.stepsoln.core.db.cases.Case.CASE_SOURCE;
import rules.*;
import com.stepsoln.core.rules.SecurityOuCaseLoadFacts;
import 	com.stepsoln.core.rules.OUGroupAssignmentData;

global com.stepsoln.core.rules.RulesResponse rulesResponse;



rule "set UW OU code and default billing frequency"
	when
		eval(true);
	then
		rulesResponse.getOuGroupAssignmentData().setUwOuCode("UWO");
		rulesResponse.setDefaultBillingFrequency("ANNUAL");
end

rule "set SVC OU code"
	when
		Number($minCount:intValue) from accumulate (SecurityOuCaseLoadFacts($count:count, type=='SVC'), min($count))
		SecurityOuCaseLoadFacts($ouCode:code, type=='SVC', count==$minCount) 	
	then
		rulesResponse.getOuGroupAssignmentData().setSvcOuCode($ouCode);
end

rule "Policy Assignment"
	when
		theCaseData:CaseData($source:caseSource in ('EXTERNAL', 'CAPTIVE', 'INTERNET'), $paperCaseFlag:paperCase,  StringUtils.isEmpty(externalCaseNumber), StringUtils.isEmpty(policyNumber));
	then
		String seqName="POLICY_NUMBER_EXTERNAL";
		
		if (Case.CASE_SOURCE.EXTERNAL.name().equalsIgnoreCase($source) && $paperCaseFlag)
		{
			seqName="POLICY_NUMBER_EPAPER";
		}
		else if (Case.CASE_SOURCE.INTERNET.name().equalsIgnoreCase($source))
		{
			seqName="POLICY_NUMBER_INTERNET";
		}
		if (Case.CASE_SOURCE.CAPTIVE.name().equalsIgnoreCase($source))
		{
			if($paperCaseFlag)
			{
				seqName="POLICY_NUMBER_IPAPER";
			}
			else
			{
				seqName="POLICY_NUMBER_CAPTIVE";
			}
		}
		rulesResponse.setPolicyNumber(seqName);
end

rule "Assign SUBMITTED cases to underwriter"
	when
		theCase:CaseData(caseStatus == 'SUBMITTED')
	then
		theCase.setSubmitApplication(true);
		theCase.setUwOu("GROUP_UWO");
end

rule "Assign AUTODECLINED cases to default underwriter"
	when
		theCase:CaseData(caseStatus == 'AUTODECLINE')
	then
		theCase.setSubmitApplication(true);
		theCase.setUwOu("DEF_GROUP_UWO");
end

rule "Assign APPROVED cases to default underwriter"
	when
		theCase:CaseData(caseStatus == 'APPROVED')
	then
		theCase.setSubmitApplication(true);
		theCase.setUwOu("DEF_GROUP_UWO");
end