import com.stepsoln.core.rules.Question;
import com.stepsoln.core.rules.EformCode;
import com.stepsoln.core.rules.CaseRulesObject;
import com.stepsoln.core.rules.RulesResponse;
import com.stepsoln.core.rules.requirements.ApplicantData;
import org.apache.commons.lang.StringUtils;
import com.stepsoln.core.util.DateUtil;
import com.stepsoln.core.db.services.util.EmployeeUtils;
import com.stepsoln.core.db.cases.*;
import com.stepsoln.core.rules.requirements.CaseData;
import com.stepsoln.core.rules.requirements.Requirement
import rules.*;
import java.util.*;
import java.math.BigDecimal;
import com.stepsoln.core.rules.requirements.DependantData

global com.stepsoln.core.rules.RulesResponse rulesResponse;

rule "Dependent Child Rider Age Limit"
	when
	  	$depAgeCnt: Number(intValue > 0) from accumulate(Question($id: id, (id.indexOf("child_date_of_birth") >= 0 && (DateUtil.calculateAgeInWeeks((java.util.Date)answer) < 2 ||  DateUtil.calculateAge((java.util.Date)answer) > 18))), 
         init( int total = 0; ),
         action( total += 1; ),
         result( new Integer( total ) ) )
	then
		rulesResponse.addRequired("Dependent child rider age should be between 2 weeks and 18 years");
end
