import com.stepsoln.core.rules.requirements.*;
import org.apache.commons.lang.StringUtils;
import com.stepsoln.core.rules.uw.*;


global com.stepsoln.core.rules.RulesResponse rulesResponse;

rule "add DSCONAPP for any UW MIB added"
	when
	    $form:RequirementForm(code == 'DSCONAPP');
	    $mibCount : Number() from accumulate(
         CaseUwMibReportableData(reportable.booleanValue()),
         init( int total = 0; ),
         action( total += 1; ),
         reverse( total -= 1; ),
         result( new Integer( total ) ) )		
    then
        if($mibCount.intValue()>0)
    		$form.setRequired(true);
    	else
    		$form.setRequired(false);
end

rule "add IXX3RDPARTY if CORRMVR is resolved"
	when
		$form:RequirementForm(code == 'IXX3RDPARTY');
		Requirement(status == 'RESOLVED', code=='MVR');
		$theCase:CaseData(contractState =='NH', caseStatus in ('INCOMPLETE','UWINCOMPLETE','SUBMITTED'))
	then
		$form.setRequired(true);
		$theCase.setUpdateCaseStatus(true);
		$theCase.setCaseStatus("SUBMITTED");
		System.out.println("!!!add IXX3RDPARTY if CORRMVR is resolved");
end	

