import com.stepsoln.core.rules.RulesResponse;
import com.stepsoln.core.rules.Question;
import com.stepsoln.core.rules.coverages.CoverageOption;
import com.stepsoln.core.rules.requirements.*;
import com.stepsoln.core.rules.uw.*;
import com.stepsoln.core.util.MathUtil
import java.util.ArrayList;
import org.apache.commons.lang.StringUtils;
import com.stepsoln.core.helper.enums.UNIT_SYSTEM;

global com.stepsoln.core.rules.RulesResponse rulesResponse;

