import com.stepsoln.core.rules.RulesResponse;
import com.stepsoln.core.rules.UserData;
import com.stepsoln.core.rules.Question;
import com.stepsoln.core.rules.coverages.*;
import com.stepsoln.core.rules.requirements.*;
import com.stepsoln.core.db.group.*;
import com.stepsoln.core.db.cases.*;
import com.stepsoln.core.util.*;
import java.math.BigDecimal;
import org.apache.commons.lang.StringUtils;
import com.stepsoln.core.rules.requirements.ApplicantData;
import com.stepsoln.core.helper.enums.UNIT_SYSTEM;
import java.lang.*;

global com.stepsoln.core.rules.RulesResponse rulesResponse;
global com.stepsoln.core.util.MathUtil math;

rule "Default LookupBuildChart to true"
when 
	 eval( true )
then
	rulesResponse.setBuildChartSuccess(true);
end

rule "Indicate to lookup build chart data with UW Class data"
salience 1000
activation-group "buildChartLookup"
	when
		$app:ApplicantData(type=='PRIMARY_INSURED')
		Question(id == "height_feet", $heightFeet:answerAsDecimal) ;
		Question(id == "height_inches", $heightInches:answerAsDecimal) ; 
		Question(id == "weight_pounds",$weightPounds:answerAsDecimal) ; 
		Question(id == "smoker_ind", $smokeInd:answerAsBoolean);	
		$uwClassData:UnderWritingClassData()
	then
	    rulesResponse.setUwClassType($uwClassData.getType());
	    $app.setLookupBuildChart(true);
		$app.setHeight($heightFeet.multiply(MathUtil.INCHES_IN_FOOT).add($heightInches).intValue());
		$app.setWeight($weightPounds.intValue());
		$app.setUnitSystem(UNIT_SYSTEM.IMPERIAL);
		$app.setTobaccoUsage($smokeInd);
		rulesResponse.addToRuleFiredList(100,"USE_BUILD_CHART_SERVICE");
end

rule "Unselected coverage options should be disabled when case is from exchange"
	when
		theCase:CaseData(PreQualiicationFlow == false);
		$coverageOption : CoverageOption()
	then
		$coverageOption.setSelectable(false);
end

rule "Do not disable coverage options when case is from pre qualification flow "
	when
		theCase:CaseData(PreQualiicationFlow == true);
		$coverageOption : CoverageOption()
	then
		$coverageOption.setSelectable(true);
end